spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    username: root
    password: 123456
#    password: urunDP2017_
#    url: jdbc:mysql://192.168.100.163:3306/data_manage?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/data_manage?useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: true  # Whether subclass-based (CGLIB) proxies are to be created (true) as

server:
  port: 8087
  servlet:
    context-path: /fileManager

config:
  upload-path: d:/

hdfs:
  url: http://192.168.100.214:50070
  dir: /uploadfile
  user-name: hadoop